server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            time: time
      - json:
          expressions:
            tag: tag
          source: attrs
      - regex:
          expression: (?P<container_name>[^/]+)
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  # Service-specific logs
  - job_name: content-manager
    static_configs:
      - targets:
          - localhost
        labels:
          job: content-manager
          service: content-manager
          __path__: /var/lib/docker/containers/*content-engine-api*/*.log

  - job_name: ai-processor
    static_configs:
      - targets:
          - localhost
        labels:
          job: ai-processor
          service: ai-processor
          __path__: /var/lib/docker/containers/*content-engine-ai*/*.log

  - job_name: web-scraper
    static_configs:
      - targets:
          - localhost
        labels:
          job: web-scraper
          service: web-scraper
          __path__: /var/lib/docker/containers/*content-engine-scraper*/*.log

  - job_name: subscriber-manager
    static_configs:
      - targets:
          - localhost
        labels:
          job: subscriber-manager
          service: subscriber-manager
          __path__: /var/lib/docker/containers/*content-engine-subscribers*/*.log

  - job_name: distributor
    static_configs:
      - targets:
          - localhost
        labels:
          job: distributor
          service: distributor
          __path__: /var/lib/docker/containers/*content-engine-distributor*/*.log